### ISSUE TITLE
Read this bzzzthe18th. 

### ISSUE THREAD

**Issue by Antmanmodisnotworkingy** [BzzzThe18th/Ant-Monke-PC#2]
You better read this bzzzthe18th you lying fuckwad.  You worked so hard on that damn networking and then made us suffer for 3 months straight. Then you say fuck you and then you get rid of the reason why anyone would us your mod.  Don't give up on it you piece of shit! Work your ass off and give us what you promised us so long ago.  Listen to face off or something so you can work at your full power.  I'm here for you, my guy!

**Comment by BzzzThe18th** [comment]
![image](https://user-images.githubusercontent.com/69125495/230229739-cc5086b2-d14a-43ea-ad16-2235fbd6125b.png)
bro I'm laughing my ass off at this, I promised jack shit, you can't just insult me and then ask nicely either
I'm not releasing networking because of dumbasses like you who will just find a way to abuse it, or people will throw it into cheats

**Comment by BzzzThe18th** [comment]
entitled children man, smh

**Comment by Antmanmodisnotworkingy** [comment]
New email who dis?

**Comment by Antmanmodisnotworkingy** [comment]
I am so sorry.  My drunk ass fucking wrote that piece of satire.  Didn't even know I wrote it until you contacted me.  I also want to ask what are your pronouns?  I could have been misgendering you this entire time.   I just feel sick when thinking about this issue.  One thing also is that we are talking about a fucking kid game.  I hope you understand that I love your content and you.   Have a great rest of 2023!



 From, Greengorilla
